<?xml version="1.0" ?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro" >
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="location_x" value="0.25" />
    <xacro:property name="location_y" value="0" />
    <xacro:property name="location_z" value="0.5" />

    <xacro:property name="bar_x" value="0.02" />
    <xacro:property name="bar_y" value="0.2" />
    <xacro:property name="bar_z" value="1.05" />
    <xacro:property name="bar_m" value="0.5" />

    <xacro:property name="vslider_x" value="0.02" />
    <xacro:property name="vslider_y" value="0.5" />
    <xacro:property name="vslider_z" value="0.05" />
    <xacro:property name="vslider_m" value="0.2" />

    <xacro:property name="hslider_x" value="0.02" />
    <xacro:property name="hslider_y" value="0.05" />
    <xacro:property name="hslider_z" value="0.05" />
    <xacro:property name="hslider_m" value="0.1" />

    <xacro:property name="finger_x" value="0.1" />
    <xacro:property name="finger_y" value="0.02" />
    <xacro:property name="finger_z" value="0.02" />
    <xacro:property name="finger_m" value="0.01" />

    <xacro:property name="tip_x" value="0.01" />
    <xacro:property name="tip_y" value="0.02" />
    <xacro:property name="tip_z" value="0.06" />
    <xacro:property name="tip_m" value="0.01" />

    <xacro:macro name="operate_device_macro" params="parent robotname">
      <joint name="joint_support_bar" type="fixed">
        <origin xyz="${location_x} ${location_y} ${location_z}" rpy="0 0 0"/>
        <parent link="${parent}"/>
        <child link="link_bar"/>
      </joint>

      <link name="link_bar">
        <visual>
          <origin xyz="${bar_x/2} 0 0" rpy="0 0 0" />
          <geometry>
            <box size="${bar_x} ${bar_y} ${bar_z}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="${bar_x/2} 0 0" rpy="0 0 0" />
          <geometry>
            <box size="${bar_x} ${bar_y} ${bar_z}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${bar_m}"/>
          <origin xyz="${bar_x/2} 0 0" rpy="0 0 0"/>
          <inertia ixx="${1/12*bar_m*(bar_y*bar_y+bar_z*bar_z)}" ixy="0" ixz="0" iyy="${1/12*bar_m*(bar_z*bar_z+bar_x*bar_x)}" iyz="0" izz="${1/12*bar_m*(bar_x*bar_x+bar_y*bar_y)}"/>
        </inertial>
      </link>

      <joint name="joint_bar_vslider" type="prismatic">
        <origin xyz="${bar_x} 0 -${bar_z/2}" rpy="0 0 0"/>
        <parent link="link_bar"/>
        <child link="link_vslider"/>
        <axis xyz="0 0 1"/>
        <limit upper="${bar_z-0.05}" lower="0.05" effort="1000.0" velocity="0.1"/>
        <dynamics damping="0" friction="2.0"/>
      </joint>
      <link name="link_vslider">
        <visual>
          <origin xyz="${vslider_x/2 + location_x} ${location_y} ${location_z}" rpy="0 0 0" />
          <geometry>
            <box size="${vslider_x} ${vslider_y} ${vslider_z}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="${vslider_x/2 + location_x} ${location_y} ${location_z}" rpy="0 0 0" />
          <geometry>
            <box size="${vslider_x} ${vslider_y} ${vslider_z}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${vslider_m}"/>
          <origin xyz="${vslider_x/2} 0 0" rpy="0 0 0"/>
          <inertia ixx="${1/12*vslider_m*(vslider_y*vslider_y+vslider_z*vslider_z)}" ixy="0" ixz="0" iyy="${1/12*vslider_m*(vslider_z*vslider_z+vslider_x*vslider_x)}" iyz="0" izz="${1/12*vslider_m*(vslider_x*vslider_x+vslider_y*vslider_y)}"/>
        </inertial>
      </link>

      <joint name="joint_slider_slider" type="prismatic">
        <origin xyz="${vslider_x} 0 0" rpy="0 0 0"/>
        <parent link="link_vslider"/>
        <child link="link_hslider"/>
        <axis xyz="0 1 0"/>
        <limit upper="${vslider_y/2}" lower="-${vslider_y/2}" effort="1000.0" velocity="0.1"/>
        <dynamics damping="0" friction="2.0"/>
      </joint>
      <link name="link_hslider">
        <visual>
          <origin xyz="${hslider_x/2 + location_x} ${location_y} ${location_z}" rpy="0 0 0" />
          <geometry>
            <box size="${hslider_x} ${hslider_y} ${hslider_z}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="${hslider_x/2 + location_x} ${location_y} ${location_z}" rpy="0 0 0" />
          <geometry>
            <box size="${hslider_x} ${hslider_y} ${hslider_z}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${hslider_m}"/>
          <origin xyz="${hslider_x/2} 0 0" rpy="0 0 0"/>
          <inertia ixx="${1/12*hslider_m*(hslider_y*hslider_y+hslider_z*hslider_z)}" ixy="0" ixz="0" iyy="${1/12*hslider_m*(hslider_z*hslider_z+hslider_x*hslider_x)}" iyz="0" izz="${1/12*hslider_m*(hslider_x*hslider_x+hslider_y*hslider_y)}"/>
        </inertial>
      </link>

      <joint name="joint_slider_finger" type="fixed">
        <origin xyz="${hslider_x} 0 0" rpy="0 0 0"/>
        <parent link="link_hslider"/>
        <child link="link_finger"/>
      </joint>

      <link name="link_finger">
        <visual>
          <origin xyz="${finger_x/2 + location_x} ${location_y} ${location_z}" rpy="0 0 0" />
          <geometry>
            <box size="${finger_x} ${finger_y} ${finger_z}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="${finger_x/2 + location_x} ${location_y} ${location_z}" rpy="0 0 0" />
          <geometry>
            <box size="${finger_x} ${finger_y} ${finger_z}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${finger_m}"/>
          <origin xyz="${finger_x/2} 0 0" rpy="0 0 0" />
          <inertia ixx="${1/12*finger_m*(finger_y*finger_y+finger_z*finger_z)}" ixy="0" ixz="0" iyy="${1/12*finger_m*(finger_z*finger_z+finger_x*finger_x)}" iyz="0" izz="${1/12*finger_m*(finger_x*finger_x+finger_y*finger_y)}"/>
        </inertial>
      </link>

      <joint name="joint_finger_tip" type="fixed">
        <origin xyz="${finger_x} 0 0" rpy="0 0 0"/>
        <parent link="link_finger"/>
        <child link="link_tip"/>
      </joint>
      <link name="link_tip">
        <visual>
          <origin xyz="${tip_x/2 + location_x} ${location_y} ${location_z-0.02}" rpy="0 0 0" />
          <geometry>
            <box size="${tip_x} ${tip_y} ${tip_z}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="${tip_x/2 + location_x} ${location_y} ${location_z-0.02}" rpy="0 0 0" />
          <geometry>
            <box size="${tip_x} ${tip_y} ${tip_z}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${tip_m}"/>
          <origin xyz="${tip_x/2} 0 -0.02" rpy="0 0 0" />
          <inertia ixx="${1/12*tip_m*(tip_y*tip_y+tip_z*tip_z)}" ixy="0" ixz="0" iyy="${1/12*tip_m*(tip_z*tip_z+tip_x*tip_x)}" iyz="0" izz="${1/12*tip_m*(tip_x*tip_x+tip_y*tip_y)}"/>
        </inertial>
      </link>

      <transmission name="vertical_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_bar_vslider">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="vertical_motor">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>

      <transmission name="horizontal_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_slider_slider">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="horizontal_motor">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>

      <gazebo reference="link_bar">
        <material>Gazebo/Orange</material>
      </gazebo>
      <gazebo reference="link_vslider">
        <material>Gazebo/Orange</material>
        <turnGravityOff>false</turnGravityOff>
      </gazebo>
      <gazebo reference="link_hslider">
        <material>Gazebo/Orange</material>
        <turnGravityOff>false</turnGravityOff>
      </gazebo>

      <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
          <robotNamespace>/${robotname}</robotNamespace>
          <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
          <legacyModeNS>true</legacyModeNS>
        </plugin>
      </gazebo>

    </xacro:macro>
</robot>
